#!/bin/sh

cd ./test || exit 1

docker-compose kill
yes | docker-compose rm
docker-compose up -d

while ! curl -s localhost:8091/pools >/dev/null 2>&1; do
	sleep 0.5
done

echo "Init cluster..."
docker exec cb_cb1_1 couchbase-cli cluster-init \
	--cluster-username=adm \
	--cluster-password=secret \
	--cluster-port=SAME \
	--cluster-ramsize=256 \
	--cluster-index-ramsize=256 \
	--services=data,index,query,fts

echo "Add nodes and rebalance..."
docker exec cb_cb1_1 couchbase-cli rebalance \
	-c localhost -u adm -p secret \
	--server-add=172.21.0.11 \
	--server-add=172.21.0.12 \
	--server-add-username=adm \
	--server-add-password=secret \
	--services=data,index,query,fts

echo "Create a bucket..."
docker exec cb_cb1_1 couchbase-cli bucket-create \
	-c localhost -u adm -p secret \
	--bucket=customer \
	--bucket-ramsize=100 \
	--enable-index-replica=1 \
	--bucket-replica=2

./generate-data &

echo "Keep adding and removing nodes and rebalancing..."
while true; do
	docker exec cb_cb1_1 couchbase-cli rebalance \
		-c localhost -u adm -p secret \
		--server-remove=172.21.0.12

	sleep 60

	docker exec cb_cb1_1 couchbase-cli rebalance \
		-c localhost -u adm -p secret \
		--server-add=172.21.0.12 \
		--server-add-username=adm \
		--server-add-password=secret \
		--services=data,index,query,fts

	sleep 60
done
